// Static, in-memory fallback demo data. Used ONLY when a live Firestore
// product query returns zero results, so a brand-new account still sees a
// populated home screen instead of a blank one. Never written to Firestore —
// safe to delete this file and its usages once real inventory exists.
import '../model/product_model.dart';

const String _demoImage = 'https://placehold.co/400x400?text=Demo+Product';

List<ProductModel> demoProducts = [
  ProductModel(
    productID: 'demo-1',
    name: 'Wireless Headphones',
    category: 'Electronics',
    description:
        'Comfortable over-ear wireless headphones with active noise isolation.',
    brandName: 'Demo Audio',
    manufacturerName: 'Demo Audio Inc.',
    countryOfOrigin: 'Demo',
    specifications: 'Bluetooth 5.0, 20 hour battery life',
    price: 79.99,
    discountedPrice: 49.99,
    discountPercentage: 38,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 1),
  ),
  ProductModel(
    productID: 'demo-2',
    name: "Men's Casual Jacket",
    category: 'Fashion',
    description: 'A lightweight jacket for everyday wear in any season.',
    brandName: 'Demo Apparel',
    manufacturerName: 'Demo Apparel Co.',
    countryOfOrigin: 'Demo',
    specifications: 'Sizes S-XXL, machine washable',
    price: 59.99,
    discountedPrice: 39.99,
    discountPercentage: 33,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 2),
  ),
  ProductModel(
    productID: 'demo-3',
    name: 'Table Lamp',
    category: 'Home',
    description: 'A warm, adjustable table lamp for any room.',
    brandName: 'Demo Home',
    manufacturerName: 'Demo Home Goods',
    countryOfOrigin: 'Demo',
    specifications: 'LED, dimmable, USB powered',
    price: 34.99,
    discountedPrice: 24.99,
    discountPercentage: 29,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 3),
  ),
  ProductModel(
    productID: 'demo-4',
    name: 'Skincare Gift Set',
    category: 'Beauty',
    description: 'A curated set of everyday skincare essentials.',
    brandName: 'Demo Beauty',
    manufacturerName: 'Demo Beauty Labs',
    countryOfOrigin: 'Demo',
    specifications: '5-piece set, all skin types',
    price: 45.00,
    discountedPrice: 29.99,
    discountPercentage: 33,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 4),
  ),
  ProductModel(
    productID: 'demo-5',
    name: 'Accent Chair',
    category: 'Furniture',
    description: 'A comfortable accent chair that fits any living space.',
    brandName: 'Demo Furniture',
    manufacturerName: 'Demo Furniture Co.',
    countryOfOrigin: 'Demo',
    specifications: 'Fabric upholstery, wooden legs',
    price: 199.99,
    discountedPrice: 149.99,
    discountPercentage: 25,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 5),
  ),
  ProductModel(
    productID: 'demo-6',
    name: 'Phone Case',
    category: 'Mobiles',
    description: 'A durable, slim-fit protective phone case.',
    brandName: 'Demo Mobile',
    manufacturerName: 'Demo Mobile Accessories',
    countryOfOrigin: 'Demo',
    specifications: 'Shockproof, wireless-charging compatible',
    price: 19.99,
    discountedPrice: 12.99,
    discountPercentage: 35,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 6),
  ),
  ProductModel(
    productID: 'demo-7',
    name: 'Travel Backpack',
    category: 'Travel',
    description: 'A spacious backpack built for weekend trips and commutes.',
    brandName: 'Demo Travel',
    manufacturerName: 'Demo Travel Gear',
    countryOfOrigin: 'Demo',
    specifications: '30L capacity, water resistant',
    price: 64.99,
    discountedPrice: 44.99,
    discountPercentage: 31,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 7),
  ),
  ProductModel(
    productID: 'demo-8',
    name: 'Bestselling Novel',
    category: 'Books',
    description: 'A gripping story that keeps readers hooked until the end.',
    brandName: 'Demo Publishing',
    manufacturerName: 'Demo Publishing House',
    countryOfOrigin: 'Demo',
    specifications: 'Paperback, 320 pages',
    price: 14.99,
    discountedPrice: 9.99,
    discountPercentage: 33,
    imagesURL: const [_demoImage],
    inStock: true,
    productSellerID: 'demo-seller',
    uploadedAt: DateTime(2024, 1, 8),
  ),
];
