// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxwjMj_ZsQZpMmVwVLSkjcEl1lrWbui8',
    appId: '1:850772114644:android:0952495acf211635300f41',
    messagingSenderId: '850772114644',
    projectId: 'fir-d77e2',
    storageBucket: 'fir-d77e2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaT-vAGF2rlTv1XldLagb8Fsg3w7wEVCI',
    appId: '1:850772114644:ios:9b1ad7ae919c77c8300f41',
    messagingSenderId: '850772114644',
    projectId: 'fir-d77e2',
    storageBucket: 'fir-d77e2.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZgH2g1_4mMXFItd7ssR1lDevl91bF4w',
    appId: '1:850772114644:web:2f4b70c065221000300f41',
    messagingSenderId: '850772114644',
    projectId: 'fir-d77e2',
    authDomain: 'fir-d77e2.firebaseapp.com',
    storageBucket: 'fir-d77e2.firebasestorage.app',
    measurementId: 'G-RGLHMRKVSW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaT-vAGF2rlTv1XldLagb8Fsg3w7wEVCI',
    appId: '1:850772114644:ios:9b1ad7ae919c77c8300f41',
    messagingSenderId: '850772114644',
    projectId: 'fir-d77e2',
    storageBucket: 'fir-d77e2.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZgH2g1_4mMXFItd7ssR1lDevl91bF4w',
    appId: '1:850772114644:web:d842595019b24143300f41',
    messagingSenderId: '850772114644',
    projectId: 'fir-d77e2',
    authDomain: 'fir-d77e2.firebaseapp.com',
    storageBucket: 'fir-d77e2.firebasestorage.app',
    measurementId: 'G-RKJ18CWPG1',
  );
}
